use utoipa::OpenApi;

use crate::transport::{
    auth::{
        BootstrapRequest, ChangePasswordRequest, DisableTotpRequest, LoginRequest, RefreshRequest,
        TotpVerifyRequest,
    },
    nodes::{
        AckRolloutRequest, CreateEnrollmentTokenRequest, CreateNodeGroupRequest, HeartbeatRequest,
        NodeEndpointRequest, NodeGroupDomainRequest, PullRolloutsRequest, RegisterNodeRequest,
        ReplaceNodeEndpointsRequest, ReplaceNodeGroupDomainsRequest, UpdateNodeGroupRequest,
    },
    subscriptions::{
        CreateSubscriptionRequest, CreateSubscriptionResponse, UpdateSubscriptionRequest,
    },
    usage::UsageBulkRequest,
    users::{CreateResellerRequest, CreateUserRequest, UpdateResellerRequest, UpdateUserRequest},
};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::transport::audit::list_audit_logs,
        crate::transport::auth::bootstrap,
        crate::transport::auth::login,
        crate::transport::auth::refresh,
        crate::transport::auth::logout,
        crate::transport::auth::logout_all,
        crate::transport::auth::begin_totp_setup,
        crate::transport::auth::verify_totp,
        crate::transport::auth::disable_totp,
        crate::transport::auth::change_password,
        crate::transport::auth::list_sessions,
        crate::transport::users::create_user,
        crate::transport::users::list_users,
        crate::transport::users::update_user,
        crate::transport::users::delete_user,
        crate::transport::users::create_reseller,
        crate::transport::users::list_resellers,
        crate::transport::users::update_reseller,
        crate::transport::users::delete_reseller,
        crate::transport::nodes::create_node_group,
        crate::transport::nodes::list_node_groups,
        crate::transport::nodes::update_node_group,
        crate::transport::nodes::delete_node_group,
        crate::transport::nodes::list_node_group_domains,
        crate::transport::nodes::replace_node_group_domains,
        crate::transport::nodes::create_enrollment_token,
        crate::transport::nodes::list_nodes,
        crate::transport::nodes::replace_node_endpoints,
        crate::transport::nodes::list_node_endpoints,
        crate::transport::nodes::list_rollouts,
        crate::transport::nodes::register_agent,
        crate::transport::nodes::heartbeat,
        crate::transport::nodes::pull_rollouts,
        crate::transport::nodes::ack_rollout,
        crate::transport::subscriptions::create_subscription,
        crate::transport::subscriptions::update_subscription,
        crate::transport::subscriptions::delete_subscription,
        crate::transport::subscriptions::rotate_subscription_link,
        crate::transport::subscriptions::list_devices,
        crate::transport::subscriptions::list_subscriptions,
        crate::transport::subscriptions::resolve_subscription,
        crate::transport::usage::ingest_usage,
        crate::transport::usage::list_usage,
        crate::transport::notifications::list_notifications
    ),
    components(schemas(
        BootstrapRequest,
        ChangePasswordRequest,
        DisableTotpRequest,
        LoginRequest,
        RefreshRequest,
        TotpVerifyRequest,
        CreateUserRequest,
        UpdateUserRequest,
        CreateResellerRequest,
        UpdateResellerRequest,
        CreateNodeGroupRequest,
        UpdateNodeGroupRequest,
        ReplaceNodeGroupDomainsRequest,
        NodeGroupDomainRequest,
        CreateEnrollmentTokenRequest,
        RegisterNodeRequest,
        HeartbeatRequest,
        PullRolloutsRequest,
        AckRolloutRequest,
        ReplaceNodeEndpointsRequest,
        NodeEndpointRequest,
        CreateSubscriptionRequest,
        UpdateSubscriptionRequest,
        CreateSubscriptionResponse,
        UsageBulkRequest
    ))
)]
pub struct ApiDoc;
