const fs = require('fs');

let content = fs.readFileSync('src/lib/i18n.ts', 'utf8');

const englishDict = {
  'nav_group.overview': 'OVERVIEW',
  'nav_group.infrastructure': 'INFRASTRUCTURE',
  'nav_group.system': 'SYSTEM',
  'dialog.management': 'Action',
  'dialog.close': 'Close',
  'dialog.warning': 'This action is irreversible and requires confirmation.',
  'dialog.cancel': 'Cancel',
  'dialog.deleting': 'Deleting...',
  'dialog.confirm': 'Confirm',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Users',
  'nav.devices': 'Devices',
  'nav.subscriptions': 'Subscriptions',
  'nav.nodes': 'Nodes',
  'nav.node_endpoints': 'Endpoints',
  'nav.rollouts': 'Rollouts',
  'nav.notifications': 'Notifications',
  'nav.logout': 'Sign Out',
  'nav.login': 'Sign In',
  'app.subtitle': 'Server & VPN Tunnel Monitoring',
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Node status, subscriptions, and sync history',
  'dashboard.label.users': 'Users',
  'dashboard.label.nodes': 'Nodes',
  'dashboard.label.subscriptions': 'Subscriptions',
  'dashboard.label.rollouts': 'Rollouts',
  'dashboard.recent.title': 'Status and Activity',
  'dashboard.recent.usage': 'Activity',
  'dashboard.recent.nodes': 'Nodes',
  'dashboard.latest_rollouts': 'Latest rollouts',
  'dashboard.security.title': 'Security',
  'dashboard.security.subtitle': 'Access management',
  'dashboard.security.change_password': 'Change Password',
  'dashboard.security.current_password': 'Current Password',
  'dashboard.security.new_password': 'New Password',
  'dashboard.security.changing': 'Updating...',
  'dashboard.security.password_for_totp': 'Password (for 2FA)',
  'dashboard.security.disable_totp': 'Disable 2FA',
  'dashboard.security.disabling': 'Disabling...',
  'dashboard.security.logout_all': 'Sign Out All Devices',
  'dashboard.security.logging_out': 'Signing out...',
  'dashboard.notifications.title': 'Events',
  'dashboard.notifications.subtitle': 'System signals',
  'dashboard.audit.title': 'Audit',
  'dashboard.audit.subtitle': 'Action history',
  'dashboard.attention.group': 'Attention',
  'dashboard.attention.title': 'Requires Review',
  'dashboard.attention.empty': 'All systems operational.',
  'dashboard.rollouts.group': 'Orchestration',
  'dashboard.rollouts.title': 'Auto-sync',
  'dashboard.rollouts.empty': 'No recent deployments.',
  'dashboard.events.group': 'Events',
  'dashboard.events.title': 'System Signals',
  'dashboard.events.empty': 'No new events.',
  'dashboard.structure.group': 'Structure',
  'dashboard.structure.title': 'System Scope',
  'dashboard.nodes.group': 'Runtimes',
  'dashboard.nodes.title': 'Node Status',
  'dashboard.nodes.empty': 'No nodes added yet.',
  'dashboard.security.group': 'Security',
  'dashboard.security.access_title': 'Account Access',
  'dashboard.security.sessions_empty': 'No other active sessions.',
  'dashboard.security.disable_success': '2FA disabled, active refresh sessions were reset.',
  'dashboard.security.password_success': 'Password updated, active refresh sessions were reset.',
  'dashboard.security.logout_all_success': 'All refresh sessions were revoked.',
  'dashboard.security.session_fallback': 'No label',
  'dashboard.security.session_created': 'Created',
  'dashboard.security.session_expires': 'Expires',
  'dashboard.attention.badge.critical': 'Critical',
  'dashboard.attention.badge.review': 'Needs review',
  'dashboard.attention.node_offline': 'Last signal: {{date}}.',
  'dashboard.attention.rollout_failed': '{{name}} failed',
  'dashboard.attention.subscription_blocked': '{{name}} is blocked',
  'dashboard.attention.subscription_blocked_description': '{{used}} of {{limit}}. Until {{date}}.',
  'dashboard.attention.subscription_warning': '{{name}} is close to the limit',
  'dashboard.attention.subscription_warning_description': '{{state}}. {{used}} of {{limit}}.',
  'dashboard.attention.subscription_expiring': '{{name}} expires soon',
  'dashboard.attention.subscription_expiring_description': 'Valid until {{date}}.',
  'dashboard.metrics.users_label': 'Users',
  'dashboard.metrics.users_hint': 'Resellers: {{count}}',
  'dashboard.metrics.subscriptions_label': 'Subscriptions',
  'dashboard.metrics.subscriptions_hint': 'With issues: {{count}}',
  'dashboard.metrics.runtimes_label': 'Runtimes',
  'dashboard.metrics.runtimes_hint': 'Total: {{total}}, offline: {{offline}}',
  'dashboard.metrics.traffic_label': 'Traffic',
  'dashboard.metrics.traffic_hint': 'Of {{limit}} total',
  'dashboard.nodes.version': 'Version {{version}}',
  'dashboard.nodes.last_seen': 'Last signal',
  'dashboard.stat.node_groups': 'Servers',
  'dashboard.stat.pending_runtimes': 'Pending Runtimes',
  'dashboard.stat.expiring_soon': 'Expiring Soon',
  'dashboard.stat.active_sessions': 'Active Sessions',
  'dashboard.stat.queued_rollouts': 'Queued Deployments',
  'devices.title': 'Devices',
  'devices.subtitle': 'Manage user devices and subscription tokens.',
  'devices.create.title': 'New Device',
  'devices.create.tenant_id': 'Tenant ID',
  'devices.create.device_name': 'Device Name',
  'devices.create.select_user': 'Select user',
  'devices.create.button': 'Add Device',
  'devices.create.loading': 'Creating...',
  'devices.list.title': 'Device List',
  'devices.list.device_token': 'Device Token',
  'devices.list.rotate_token': 'Rotate Token',
  'devices.list.rotating': 'Rotating...',
  'devices.status.suspended': 'Suspended',
  'devices.status.active': 'Active',
  'devices.unauthorized': 'Devices section is restricted',
  'login.title': 'Sign In',
  'login.subtitle': 'Sign in to access control plane',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.totp_code': '2FA Code',
  'login.button': 'Sign In',
  'login.loading': 'Verifying...',
  'login.return': 'Back to login',
  'login.totp_setup': 'Setup 2FA',
  'login.secret': 'Secret',
  'login.otp_url': 'OTPAuth URL',
  'login.totp_verifying': 'Verifying...',
  'login.totp_verify': 'Verify 2FA',
  'login.slogan': 'High-performance control plane for server and subscription orchestration',
  'auth.session_expired': 'Session expired',
  'nodes.title': 'Platform Nodes',
  'nodes.subtitle': 'Manage server nodes and runtimes for the VPN infrastructure.',
  'nodes.create.title': 'Register Agent',
  'nodes.create.select_tenant': 'Select Tenant',
  'nodes.create.select_group': 'Select Server',
  'nodes.create.select_engine': 'Proxy Engine',
  'nodes.create.button': 'Reveal Token',
  'nodes.create.loading': 'Generating...',
  'nodes.create.token_hint': 'Copy this install block to the server and run it.',
  'nodes.list.title': 'Server Nodes',
  'nodes.list.last_seen': 'Last Seen',
  'nodes.list.endpoints': 'config',
  'nodes.groups.title': 'Servers',
  'nodes.groups.create': 'Add Server',
  'nodes.groups.name': 'Server Name',
  'nodes.groups.creating': 'Creating...',
  'nodes.runtime.missing': 'Not registered',
  'nodes.unauthorized': 'Nodes section is restricted',
  'node_endpoints.title': 'Domains and Endpoints',
  'node_endpoints.subtitle': 'Configure domains, modes, SNI, and Host for the selected server. The panel rebuilds endpoints automatically after saving.',
  'node_endpoints.not_found': 'Select a node first',
  'node_endpoints.create': 'Add Inbound',
  'node_endpoints.save': 'Save',
  'node_endpoints.saving': 'Saving...',
  'node_endpoints.unauthorized': 'Endpoints section is restricted',
  'node_endpoints.error.server_required': 'Select a server node first.',
  'node_endpoints.saved': 'Domain rules saved: {{count}}. Endpoints were rebuilt automatically.',
  'node_endpoints.toggled': 'Endpoint state updated.',
  'node_endpoints.select_server': 'Select server',
  'node_endpoints.configure': 'Configure domains',
  'node_endpoints.runtime_missing': 'Not registered',
  'node_endpoints.runtime_version': 'Version {{version}}',
  'node_endpoints.runtime_last_seen': 'Last signal',
  'node_endpoints.domains_empty': 'No domains yet. Open settings and fill in the required modes in one place.',
  'node_endpoints.server_required': 'Select a server first.',
  'node_endpoints.generated_title': 'Generated endpoints',
  'node_endpoints.generated_empty': 'Save the domains and the panel will immediately build endpoints for the selected server.',
  'node_endpoints.dialog.title': 'Server domains for {{name}}',
  'node_endpoints.dialog.title_empty': 'Domain settings',
  'node_endpoints.dialog.description': 'All modes, SNI, and Host are configured in one dialog. After saving, the panel rebuilds endpoints automatically.',
  'node_endpoints.dialog.add_rule': 'Add rule',
  'node_endpoints.dialog.reset_preset': 'Starter pack',
  'node_endpoints.dialog.rules': 'Rules',
  'node_endpoints.dialog.mode': 'Mode',
  'node_endpoints.rule_new': 'New rule',
  'node_endpoints.domain': 'Domain',
  'node_endpoints.alias': 'Alias',
  'node_endpoints.server_names': 'SNI / server_name',
  'node_endpoints.rule_help': 'Empty SNI and Host fields do not break the rule. If you leave them blank, the panel will substitute the domain automatically.',
  'node_endpoints.rule_delete': 'Delete rule',
  'node_endpoints.rule_empty': 'No rule selected. Add a new one or fill in the starter pack.',
  'node_endpoints.endpoint_security': 'Security',
  'node_endpoints.endpoint_reality_key': 'Reality key',
  'node_endpoints.endpoint_reality_ready': 'ready',
  'node_endpoints.endpoint_reality_unused': 'not required',
  'node_endpoints.select_node': 'Select node',
  'node_endpoints.add': 'Add endpoint',
  'node_endpoints.remove': 'Remove',
  'node_endpoints.enabled': 'Enabled',
  'node_endpoints.listen_host': 'Listen host',
  'node_endpoints.listen_port': 'Listen port',
  'node_endpoints.public_host': 'Public host',
  'node_endpoints.public_port': 'Public port',
  'node_endpoints.server_name': 'Server name',
  'node_endpoints.host_header': 'Host header',
  'node_endpoints.path': 'Path',
  'node_endpoints.service_name': 'Service name',
  'node_endpoints.flow': 'Flow manager',
  'node_endpoints.reality_public_key': 'Reality Public Key',
  'node_endpoints.reality_private_key': 'Reality Private Key',
  'node_endpoints.reality_short_id': 'Reality Short ID',
  'node_endpoints.fingerprint': 'Fingerprint',
  'node_endpoints.alpn': 'ALPN (csv)',
  'node_endpoints.cipher': 'Cipher spec',
  'node_endpoints.modes.direct.title': 'Direct',
  'node_endpoints.modes.direct.description': 'Use this mode when the domain points directly to the server and works without CDN or proxy.',
  'node_endpoints.modes.direct.domain_hint': 'Specify the domain that already points to the server in DNS only mode.',
  'node_endpoints.modes.direct.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.direct.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.direct.host_header_hint': 'One entry per line. If left empty, Host will match the domain.',
  'node_endpoints.modes.legacy_direct.title': 'Legacy direct',
  'node_endpoints.modes.legacy_direct.description': 'Direct connection without gRPC. Use it if you only need the classic set without gRPC variants.',
  'node_endpoints.modes.legacy_direct.domain_hint': 'Specify the domain that points directly to the server without a proxy.',
  'node_endpoints.modes.legacy_direct.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.legacy_direct.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.legacy_direct.host_header_hint': 'One entry per line. If left empty, Host will match the domain.',
  'node_endpoints.modes.cdn.title': 'CDN',
  'node_endpoints.modes.cdn.description': 'Use it for a domain behind CDN or any proxy mode. The panel will prepare a TLS-oriented set of endpoints.',
  'node_endpoints.modes.cdn.domain_hint': 'Specify the domain that is issued to users and works through a proxy or CDN.',
  'node_endpoints.modes.cdn.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.cdn.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.cdn.host_header_hint': 'One entry per line. If left empty, Host will match the domain.',
  'node_endpoints.modes.auto_cdn.title': 'Auto CDN',
  'node_endpoints.modes.auto_cdn.description': 'Works like CDN mode, but the public address is resolved automatically from the domain DNS.',
  'node_endpoints.modes.auto_cdn.domain_hint': 'Specify a domain whose current IP can be obtained via DNS.',
  'node_endpoints.modes.auto_cdn.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.auto_cdn.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.auto_cdn.host_header_hint': 'One entry per line. If left empty, Host will match the domain.',
  'node_endpoints.modes.relay.title': 'Relay',
  'node_endpoints.modes.relay.description': 'Suitable for a topology with an intermediate server. The panel will build a standard set of endpoints with a relay domain.',
  'node_endpoints.modes.relay.domain_hint': 'Specify the external domain through which users access the relay topology.',
  'node_endpoints.modes.relay.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.relay.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.relay.host_header_hint': 'One entry per line. If left empty, Host will match the domain.',
  'node_endpoints.modes.worker.title': 'Worker',
  'node_endpoints.modes.worker.description': 'Builds a worker topology for WS and HTTP Upgrade. Useful when you need an external Host and separate SNI values.',
  'node_endpoints.modes.worker.domain_hint': 'Specify the domain through which traffic will enter the worker topology.',
  'node_endpoints.modes.worker.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.worker.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.worker.host_header_hint': 'One entry per line. If there are fewer lines, the panel will reuse the first Host for the remaining variants.',
  'node_endpoints.modes.reality.title': 'Reality',
  'node_endpoints.modes.reality.description': 'A separate endpoint with Reality keys is created for each SNI in the list. Keys are generated automatically.',
  'node_endpoints.modes.reality.domain_hint': 'Specify the domain that will be the public address for Reality connections.',
  'node_endpoints.modes.reality.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.reality.server_name_hint': 'One entry per line. Each line creates a separate Reality endpoint.',
  'node_endpoints.modes.reality.host_header_hint': 'Not used for Reality and can be left empty.',
  'node_endpoints.modes.fake.title': 'Fake site',
  'node_endpoints.modes.fake.description': 'Use it when you need a masking domain and a separate SNI for evasive topologies.',
  'node_endpoints.modes.fake.domain_hint': 'Specify the external domain that clients will receive as the public address.',
  'node_endpoints.modes.fake.alias_hint': 'A short name for the panel and configs. You can leave it empty.',
  'node_endpoints.modes.fake.server_name_hint': 'One entry per line. If left empty, the panel will use the domain itself.',
  'node_endpoints.modes.fake.host_header_hint': 'One entry per line. If left empty, Host will match the domain.',
  'rollouts.title': 'Configuration Rollouts',
  'rollouts.subtitle': 'Compilation of configs and deployment queue for orchestrator.',
  'rollouts.create.title': 'New Rollout',
  'rollouts.create.select_node': 'Select node',
  'rollouts.create.revision_name': 'Revision Name',
  'rollouts.create.target_path': 'Target Path',
  'rollouts.create.enabled_endpoints': 'Active inbounds',
  'rollouts.create.active_credentials': 'Active accounts',
  'rollouts.create.button': 'Launch Rollout',
  'rollouts.create.loading': 'Queuing...',
  'rollouts.list.title': 'Rollout Status',
  'rollouts.list.revision': 'revision',
  'rollouts.unauthorized': 'Rollouts section is restricted',
  'rollouts.error.node_required': 'Select a node first',
  'rollouts.error.no_endpoints': 'Selected node has zero enabled endpoints',
  'rollouts.error.no_credentials': 'No active subscriptions for this node',
  'subscriptions.title': 'Subscriptions',
  'subscriptions.subtitle': 'Manage subscriptions, traffic limits, and stable import links for browsers and VPN clients.',
  'subscriptions.create.title': 'Create Subscription',
  'subscriptions.create.name': 'Subscription Name',
  'subscriptions.create.quota': 'Traffic Limit (MB)',
  'subscriptions.create.select_device': 'Select device',
  'subscriptions.create.button': 'Create Subscription',
  'subscriptions.create.loading': 'Creating...',
  'subscriptions.create.description': 'The access plan is created immediately with a limit, expiration date, and a ready import link.',
  'subscriptions.create.select_user': 'Select user',
  'subscriptions.create.name_placeholder': 'Plan name',
  'subscriptions.create.note_placeholder': 'Admin note',
  'subscriptions.create.limit_placeholder': 'Traffic limit, GB',
  'subscriptions.create.days_placeholder': 'Plan days',
  'subscriptions.create.default_name_for_user': '{{name}} access',
  'subscriptions.create.summary_limit': 'Limit: {{value}}',
  'subscriptions.create.summary_limit_empty': 'not set',
  'subscriptions.create.summary_days': 'Duration: {{value}} days',
  'subscriptions.create.preview_expires': 'Valid until',
  'subscriptions.create.preview_expires_empty': 'set the plan duration',
  'subscriptions.create.error.package_days_required': 'Set the plan duration in days',
  'subscriptions.create.created': 'Subscription {{name}} created.',
  'subscriptions.list.title': 'Access Plans',
  'subscriptions.list.rotate_link': 'Reset Link',
  'subscriptions.list.rotating': 'Resetting...',
  'subscriptions.list.quota_warning': 'Warning',
  'subscriptions.unauthorized': 'Subscriptions section is restricted',
  'subscriptions.delivery_url': 'Import URL',
  'subscriptions.success_link_label': 'Ready Subscription Link',
  'subscriptions.default_name': 'Subscription',
  'subscriptions.rotate.updated': 'Subscription link updated.',
  'subscriptions.artifact.placeholder': 'Issue or rotate the link first.',
  'subscriptions.artifact.curl': 'Curl',
  'subscriptions.artifact.hint': 'The same link opens a subscription page in the browser and imports in a VPN client without extra headers.',
  'subscriptions.status.active': 'Active',
  'subscriptions.status.suspended': 'Suspended',
  'subscriptions.expires_badge': 'Until {{date}}',
  'subscriptions.user': 'User: {{name}}',
  'subscriptions.stats.limit': 'Limit',
  'subscriptions.stats.used': 'Used',
  'subscriptions.stats.expires': 'Valid until',
  'subscriptions.link.placeholder': 'The link has not been issued yet.',
  'subscriptions.link.hint': 'Open this link in the browser to show the subscription page. You can paste the same link into the app for import and updates.',
  'subscriptions.empty': 'No subscriptions yet.',
  'subscriptions.edit.title': 'Edit Subscription',
  'subscriptions.edit.description': 'Change the access plan parameters and save the new limits.',
  'subscriptions.edit.name_placeholder': 'Plan name',
  'subscriptions.edit.note_placeholder': 'Admin note',
  'subscriptions.edit.limit_placeholder': 'Traffic limit, GB',
  'subscriptions.edit.suspend': 'Suspend subscription',
  'subscriptions.edit.pending': 'Saving...',
  'subscriptions.update.error.no_selection': 'No subscription selected',
  'subscriptions.update.error.invalid_expiration': 'Set a valid expiration date',
  'subscriptions.update.updated': 'Subscription {{name}} updated.',
  'subscriptions.delete.title': 'Delete subscription',
  'subscriptions.delete.description': 'Subscription {{name}} will be deleted. The linked import URL will stop working.',
  'subscriptions.delete.deleted': 'Subscription deleted.',
  'subscriptions.delete.pending': 'Deleting...',
  'users.title': 'Users',
  'users.subtitle': 'Manage accounts, access tiers, and resellers.',
  'users.create.title': 'New User',
  'users.create.email': 'Email',
  'users.create.name': 'Display Name',
  'users.create.password': 'Password',
  'users.create.role': 'Role',
  'users.create.button': 'Add User',
  'users.create.loading': 'Adding...',
  'users.resellers.title': 'New Reseller',
  'users.resellers.tenant_name': 'Tenant Name',
  'users.resellers.button': 'Add Reseller',
  'users.resellers.loading': 'Creating...',
  'users.list.title': 'Current Users',
  'users.list.role': 'role',
  'users.unauthorized': 'Users section is restricted',
  'users.select_tenant': 'Current tenant / global scope',
  'users.table.user': 'User',
  'users.table.role': 'Role',
  'users.table.tenant': 'Tenant Scope',
  'users.table.status': 'Status',
  'users.table.totp': 'TOTP Protection',
  'users.table.created': 'Created At',
  'notifications.title': 'Notifications & Monitoring',
  'notifications.subtitle': 'Internal event log, quota states, and identity provider audit.',
  'notifications.unauthorized': 'Notifications section is restricted',
  'notifications.events.title': 'System Events',
  'notifications.quota.title': 'Quota Monitor',
  'notifications.audit.title': 'Audit Log',
  'public_subscription.group': 'Subscription',
  'public_subscription.subtitle': 'Open this link in the browser to view subscription details. Paste the same link into a VPN client to import and keep updating the profile.',
  'public_subscription.loading_title': 'Loading subscription',
  'public_subscription.loading_subtitle': 'Fetching the latest data for this link.',
  'public_subscription.error_title': 'Subscription not found',
  'public_subscription.error_subtitle': 'This link may have been rotated, revoked, or expired.',
  'public_subscription.status_label': 'Status',
  'public_subscription.status.active': 'Active',
  'public_subscription.status.suspended': 'Suspended',
  'public_subscription.status.expired': 'Expired',
  'public_subscription.limit': 'Limit',
  'public_subscription.used': 'Used',
  'public_subscription.expires': 'Valid until',
  'public_subscription.link_group': 'Import',
  'public_subscription.link_title': 'App link',
  'public_subscription.delivery_url': 'Link',
  'public_subscription.copy': 'Copy link',
  'public_subscription.copied': 'Copied',
  'public_subscription.raw': 'Open raw',
  'public_subscription.link_hint': 'The same link works both as a browser page and as an import URL in VPN clients.',
  'public_subscription.note_group': 'Details',
  'public_subscription.note_title': 'Note',
  'public_subscription.note_empty': 'No note.',
  'status.success': 'Success',
  'status.error': 'Error',
  'status.pending': 'Pending',
  'status.online': 'Online',
  'status.offline': 'Offline'
};

const newBaseEn = `const baseEn = ` + JSON.stringify(englishDict, null, 2) + `;`;

// Match the existing baseEn block and replace it
content = content.replace(/const baseEn = \{[\s\S]*?\};/, newBaseEn);

fs.writeFileSync('src/lib/i18n.ts', content);
