const fs = require('fs');

let content = fs.readFileSync('src/lib/i18n.ts', 'utf8');

const englishDict = {
  'nav_group.overview': 'OVERVIEW',
  'nav_group.infrastructure': 'INFRASTRUCTURE',
  'nav_group.system': 'SYSTEM',
  'dialog.management': 'Action',
  'dialog.close': 'Close',
  'dialog.warning': 'This action is irreversible and requires confirmation.',
  'dialog.cancel': 'Cancel',
  'dialog.deleting': 'Deleting...',
  'dialog.confirm': 'Confirm',
  'nav.dashboard': 'Dashboard',
  'nav.users': 'Users',
  'nav.devices': 'Devices',
  'nav.subscriptions': 'Subscriptions',
  'nav.nodes': 'Nodes',
  'nav.node_endpoints': 'Endpoints',
  'nav.rollouts': 'Rollouts',
  'nav.notifications': 'Notifications',
  'nav.logout': 'Sign Out',
  'nav.login': 'Sign In',
  'app.subtitle': 'Server & VPN Tunnel Monitoring',
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Node status, subscriptions, and sync history',
  'dashboard.label.users': 'Users',
  'dashboard.label.nodes': 'Nodes',
  'dashboard.label.subscriptions': 'Subscriptions',
  'dashboard.label.rollouts': 'Rollouts',
  'dashboard.recent.title': 'Status and Activity',
  'dashboard.recent.usage': 'Activity',
  'dashboard.recent.nodes': 'Nodes',
  'dashboard.latest_rollouts': 'Latest rollouts',
  'dashboard.security.title': 'Security',
  'dashboard.security.subtitle': 'Access management',
  'dashboard.security.change_password': 'Change Password',
  'dashboard.security.current_password': 'Current Password',
  'dashboard.security.new_password': 'New Password',
  'dashboard.security.changing': 'Updating...',
  'dashboard.security.password_for_totp': 'Password (for 2FA)',
  'dashboard.security.disable_totp': 'Disable 2FA',
  'dashboard.security.disabling': 'Disabling...',
  'dashboard.security.logout_all': 'Sign Out All Devices',
  'dashboard.security.logging_out': 'Signing out...',
  'dashboard.notifications.title': 'Events',
  'dashboard.notifications.subtitle': 'System signals',
  'dashboard.audit.title': 'Audit',
  'dashboard.audit.subtitle': 'Action history',
  'dashboard.attention.group': 'Attention',
  'dashboard.attention.title': 'Requires Review',
  'dashboard.attention.empty': 'All systems operational.',
  'dashboard.rollouts.group': 'Orchestration',
  'dashboard.rollouts.title': 'Auto-sync',
  'dashboard.rollouts.empty': 'No recent deployments.',
  'dashboard.events.group': 'Events',
  'dashboard.events.title': 'System Signals',
  'dashboard.events.empty': 'No new events.',
  'dashboard.structure.group': 'Structure',
  'dashboard.structure.title': 'System Scope',
  'dashboard.nodes.group': 'Runtimes',
  'dashboard.nodes.title': 'Node Status',
  'dashboard.nodes.empty': 'No nodes added yet.',
  'dashboard.security.group': 'Security',
  'dashboard.security.access_title': 'Account Access',
  'dashboard.security.sessions_empty': 'No other active sessions.',
  'dashboard.stat.node_groups': 'Server Groups',
  'dashboard.stat.pending_runtimes': 'Pending Runtimes',
  'dashboard.stat.expiring_soon': 'Expiring Soon',
  'dashboard.stat.active_sessions': 'Active Sessions',
  'dashboard.stat.queued_rollouts': 'Queued Deployments',
  'devices.title': 'Devices',
  'devices.subtitle': 'Manage user devices and subscription tokens.',
  'devices.create.title': 'New Device',
  'devices.create.tenant_id': 'Tenant ID',
  'devices.create.device_name': 'Device Name',
  'devices.create.select_user': 'Select user',
  'devices.create.button': 'Add Device',
  'devices.create.loading': 'Creating...',
  'devices.list.title': 'Device List',
  'devices.list.device_token': 'Device Token',
  'devices.list.rotate_token': 'Rotate Token',
  'devices.list.rotating': 'Rotating...',
  'devices.status.suspended': 'Suspended',
  'devices.status.active': 'Active',
  'devices.unauthorized': 'Devices section is restricted',
  'login.title': 'Sign In',
  'login.subtitle': 'Sign in to access control plane',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.totp_code': '2FA Code',
  'login.button': 'Sign In',
  'login.loading': 'Verifying...',
  'login.return': 'Back to login',
  'login.totp_setup': 'Setup 2FA',
  'login.secret': 'Secret',
  'login.otp_url': 'OTPAuth URL',
  'login.totp_verifying': 'Verifying...',
  'login.totp_verify': 'Verify 2FA',
  'login.slogan': 'High-performance control plane for server and subscription orchestration',
  'nodes.title': 'Platform Nodes',
  'nodes.subtitle': 'Manage VPN infrastructure, token access, and status.',
  'nodes.create.title': 'Register Agent',
  'nodes.create.select_tenant': 'Select Tenant',
  'nodes.create.select_group': 'Select Node Group',
  'nodes.create.select_engine': 'Proxy Engine',
  'nodes.create.button': 'Reveal Token',
  'nodes.create.loading': 'Generating...',
  'nodes.create.token_hint': 'Use this token to register your node via CLI',
  'nodes.list.title': 'Registered Agents',
  'nodes.list.last_seen': 'Last Seen',
  'nodes.list.endpoints': 'config',
  'nodes.groups.title': 'Node Groups',
  'nodes.groups.create': 'Create Group',
  'nodes.groups.name': 'Group Name',
  'nodes.groups.creating': 'Creating...',
  'nodes.unauthorized': 'Nodes section is restricted',
  'node_endpoints.title': 'Endpoint Configuration',
  'node_endpoints.subtitle': 'Detailed routing for ports, protocols, and TLS Reality masking.',
  'node_endpoints.not_found': 'Select a node first',
  'node_endpoints.create': 'Add Inbound',
  'node_endpoints.save': 'Save',
  'node_endpoints.saving': 'Saving...',
  'node_endpoints.unauthorized': 'Endpoints section is restricted',
  'node_endpoints.select_node': 'Select node',
  'node_endpoints.add': 'Add endpoint',
  'node_endpoints.remove': 'Remove',
  'node_endpoints.enabled': 'Enabled',
  'node_endpoints.listen_host': 'Listen host',
  'node_endpoints.listen_port': 'Listen port',
  'node_endpoints.public_host': 'Public host',
  'node_endpoints.public_port': 'Public port',
  'node_endpoints.server_name': 'Server name',
  'node_endpoints.host_header': 'Host header',
  'node_endpoints.path': 'Path',
  'node_endpoints.service_name': 'Service name',
  'node_endpoints.flow': 'Flow manager',
  'node_endpoints.reality_public_key': 'Reality Public Key',
  'node_endpoints.reality_private_key': 'Reality Private Key',
  'node_endpoints.reality_short_id': 'Reality Short ID',
  'node_endpoints.fingerprint': 'Fingerprint',
  'node_endpoints.alpn': 'ALPN (csv)',
  'node_endpoints.cipher': 'Cipher spec',
  'rollouts.title': 'Configuration Rollouts',
  'rollouts.subtitle': 'Compilation of configs and deployment queue for orchestrator.',
  'rollouts.create.title': 'New Rollout',
  'rollouts.create.select_node': 'Select node',
  'rollouts.create.revision_name': 'Revision Name',
  'rollouts.create.target_path': 'Target Path',
  'rollouts.create.enabled_endpoints': 'Active inbounds',
  'rollouts.create.active_credentials': 'Active accounts',
  'rollouts.create.button': 'Launch Rollout',
  'rollouts.create.loading': 'Queuing...',
  'rollouts.list.title': 'Rollout Status',
  'rollouts.list.revision': 'revision',
  'rollouts.unauthorized': 'Rollouts section is restricted',
  'rollouts.error.node_required': 'Select a node first',
  'rollouts.error.no_endpoints': 'Selected node has zero enabled endpoints',
  'rollouts.error.no_credentials': 'No active subscriptions for this node',
  'subscriptions.title': 'Subscriptions',
  'subscriptions.subtitle': 'Manage user traffic limits and V2Ray / Sing-box delivery urls.',
  'subscriptions.create.title': 'New Subscription',
  'subscriptions.create.name': 'Plan Name',
  'subscriptions.create.quota': 'Traffic Limit (MB)',
  'subscriptions.create.select_device': 'Select device',
  'subscriptions.create.button': 'Create Subscription',
  'subscriptions.create.loading': 'Creating...',
  'subscriptions.list.title': 'Access Plans',
  'subscriptions.list.rotate_link': 'Reset Link',
  'subscriptions.list.rotating': 'Resetting...',
  'subscriptions.list.quota_warning': 'Warning',
  'subscriptions.unauthorized': 'Subscriptions section is restricted',
  'subscriptions.delivery_url': 'Emergency Delivery URL',
  'subscriptions.success_link_label': 'Ready Subscription Link',
  'users.title': 'Users',
  'users.subtitle': 'Manage accounts, access tiers, and resellers.',
  'users.create.title': 'New User',
  'users.create.email': 'Email',
  'users.create.name': 'Display Name',
  'users.create.password': 'Password',
  'users.create.role': 'Role',
  'users.create.button': 'Add User',
  'users.create.loading': 'Adding...',
  'users.resellers.title': 'New Reseller',
  'users.resellers.tenant_name': 'Tenant Name',
  'users.resellers.button': 'Add Reseller',
  'users.resellers.loading': 'Creating...',
  'users.list.title': 'Current Users',
  'users.list.role': 'role',
  'users.unauthorized': 'Users section is restricted',
  'users.select_tenant': 'Current tenant / global scope',
  'users.table.user': 'User',
  'users.table.role': 'Role',
  'users.table.tenant': 'Tenant Scope',
  'users.table.status': 'Status',
  'users.table.totp': 'TOTP Protection',
  'users.table.created': 'Created At',
  'notifications.title': 'Notifications & Monitoring',
  'notifications.subtitle': 'Internal event log, quota states, and identity provider audit.',
  'notifications.unauthorized': 'Notifications section is restricted',
  'notifications.events.title': 'System Events',
  'notifications.quota.title': 'Quota Monitor',
  'notifications.audit.title': 'Audit Log',
  'status.success': 'Success',
  'status.error': 'Error',
  'status.pending': 'Pending',
  'status.online': 'Online',
  'status.offline': 'Offline'
};

const newBaseEn = `const baseEn = ` + JSON.stringify(englishDict, null, 2) + `;`;

// Match the existing baseEn block and replace it
content = content.replace(/const baseEn = \{[\s\S]*?\};/, newBaseEn);

fs.writeFileSync('src/lib/i18n.ts', content);
